# Generated by Django 5.0.4 on 2024-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='noticias_archivos/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='nombre_redactor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titular',
            field=models.CharField(max_length=100),
        ),
    ]
