# Generated by Django 5.0.4 on 2024-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticia_archivo_adjunto_alter_noticia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='archivo_adjunto',
            field=models.FileField(default='media/noticias_archivos/limon.jpg', upload_to='noticias_archivos/'),
        ),
    ]
