# Generated by Django 5.0.4 on 2024-06-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_noticia_archivo_adjunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombreprod',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='price',
        ),
    ]
