# Generated by Django 5.0.4 on 2024-07-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
