# Generated by Django 5.0.4 on 2024-07-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscription_cart_cartitem_cart_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(),
        ),
    ]
