# Generated by Django 5.0.4 on 2024-07-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_purchasehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
    ]
