# Generated by Django 5.0.4 on 2024-07-13 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_total_amount_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subscription'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
