# Generated by Django 5.0.4 on 2024-07-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_order_items_remove_purchasehistory_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='total',
            new_name='total_amount',
        ),
    ]
