# Generated by Django 5.0.4 on 2024-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_total_purchasehistory_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_clp',
            field=models.IntegerField(default=0),
        ),
    ]
