# Generated by Django 5.0.4 on 2024-07-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_purchaseitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
