# Generated by Django 5.0.4 on 2024-07-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_subscription_price_usd_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_usd',
            field=models.IntegerField(default=0),
        ),
    ]
