# Generated by Django 5.0.4 on 2024-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_subscription_price_subscription_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
